// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: hello.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// XClient is the client API for X service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XClient interface {
	Hello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
}

type xClient struct {
	cc grpc.ClientConnInterface
}

func NewXClient(cc grpc.ClientConnInterface) XClient {
	return &xClient{cc}
}

func (c *xClient) Hello(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := c.cc.Invoke(ctx, "/proto.x/hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// XServer is the server API for X service.
// All implementations must embed UnimplementedXServer
// for forward compatibility
type XServer interface {
	Hello(context.Context, *Req) (*Resp, error)
	mustEmbedUnimplementedXServer()
}

// UnimplementedXServer must be embedded to have forward compatible implementations.
type UnimplementedXServer struct {
}

func (UnimplementedXServer) Hello(context.Context, *Req) (*Resp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedXServer) mustEmbedUnimplementedXServer() {}

// UnsafeXServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XServer will
// result in compilation errors.
type UnsafeXServer interface {
	mustEmbedUnimplementedXServer()
}

func RegisterXServer(s grpc.ServiceRegistrar, srv XServer) {
	s.RegisterService(&X_ServiceDesc, srv)
}

func _X_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(XServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.x/hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(XServer).Hello(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

// X_ServiceDesc is the grpc.ServiceDesc for X service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var X_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.x",
	HandlerType: (*XServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "hello",
			Handler:    _X_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
